# Generated by Django 3.0.5 on 2020-04-24 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('age', models.IntegerField(verbose_name='age')),
                ('username', models.CharField(max_length=10, verbose_name='username')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='price')),
                ('amount', models.IntegerField(verbose_name='amount')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceType', models.CharField(max_length=30, verbose_name='servicetype')),
                ('description', models.CharField(max_length=1000, verbose_name='description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='price')),
            ],
        ),
    ]
